name: shared_preferences_linux
publish_to: none
description: Linux implementation of the shared_preferences plugin
repository: https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences_linux
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22
version: 2.3.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    implements: shared_preferences
    platforms:
      linux:
        dartPluginClass: SharedPreferencesLinux

dependencies:
  file: ^7.0.0
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider_linux:
    git: https://github.com/kumsumit/path_provider_linux.git
  path_provider_platform_interface:
    git: https://github.com/kumsumit/path_provider_platform_interface.git
  shared_preferences_platform_interface:
    git: https://github.com/kumsumit/shared_preferences_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - persistence
  - shared-preferences
  - storage
